package mx.com.xoco.nuniez.entities;

import lombok.Data;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.id.SelectGenerator;

import javax.persistence.*;

@Entity
@Table(name = "edu_course")
@Data
public class EduCourse {
/* TableGenerator - Initial approach */
//    @TableGenerator(
//            name = "course_gen",
//            table = "id_gen_table",
//            pkColumnName = "gen_key",
//            pkColumnValue = "edu_course_id",
//            valueColumnName = "gen_value",
//            allocationSize = 30
//    )
/* TableGenerator - full spec */
//    @TableGenerator(
//            name = "course_gen",
//            table = "cbs_api_sequences",
//            pkColumnName = "sequence_name",
//            pkColumnValue = "edu_course_id",
//            valueColumnName = "next_val",
//            allocationSize = 30
//    )
/* TableGenerator - min spec */
//    @TableGenerator(
//            name = "course_gen",
//            table = "cbs_api_course_sequences",
//            allocationSize = 30
//    )
/* SelectGenerator - id generated by trigger */
//    @GeneratedValue(generator = "triggered-by-db")
//    @GenericGenerator(
//            name = "triggered-by-db",
//            strategy = "select",
//            parameters = {
//                    @org.hibernate.annotations.Parameter(name = "key", value = "courseName")
//            }
//    )
/* SequenceStyleGenerator - like table generator spec */
    @Id
    @GeneratedValue(generator = "edu_course_id_seq_gen")
    @GenericGenerator (
            name = "edu_course_id_seq_gen",
            strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator",
            parameters = {
                    @org.hibernate.annotations.Parameter(name = "sequence_name", value = "sequence"),
                    @org.hibernate.annotations.Parameter(name = "increment_size", value = "1"),
                    @org.hibernate.annotations.Parameter(name = "force_table_use", value = "true"),
                    @org.hibernate.annotations.Parameter(name = "value_column", value = "cur_value"),
            }
    )
    private int id;

    @Column(name = "course_name")
    private String courseName;

    @Column(name = "course_duration")
    private int duration;
}
